events {

}

http{
    # here backend is just a variable which contains server1:700, server2:7000, server3:7000 anyof these 
    upstream backend{
        server server1:7000;
        server server2:7000;
        server server3:7000;
    }
    server{
        listen 80;
        location /{
            # proxy_pass http://server:7000;
            proxy_pass http://backend;
        }
    }
}

#  boiler plate of nginx
