services:
  nginx:
    image: nginx 
    ports:
      - 8000:80
      # using Bind Mount whatevery we type in nginx.conf locally will mount to the same filein the container 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
